Update fzf config & git completion

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -6,9 +6,9 @@
 
 # Personal $HOME/.bashrc file
 # Author: Kevin Bowen <kevin.bowen@gmail.com>
-# Version: 3.0.4
+# Version: 3.0.5
 # Source : http://codeberg.org/kevinbowen/dotfiles
-# Last modified: 20250311
+# Last modified: 20250322
 # 
 #                               Sections
 #
@@ -131,16 +131,16 @@ export NO_AT_BRIDGE=1
 # PostgreSQL
 export PGPASS="/home/kbowen/.pgpass"
 
-# NVM installation - 20221004
+# NVM installation
 # https://github.com/nvm-sh/nvm
 NVM_DIR="$HOME/.config/nvm"
 export NVM_DIR
 # shellcheck source=/dev/null
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 # shellcheck source=/dev/null
-[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
 
-# pyenv installation - 20220922
+# pyenv installation
 export PYENV_ROOT="$HOME/.pyenv"
 [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
 export PATH="$PYENV_ROOT/shims:$PATH"
@@ -149,36 +149,70 @@ eval "$(pyenv init -)"
 
 export PYTHONSTARTUP=~/.pythonstartup
 
-# Ruby - rbenv - 20230625
+# Ruby
 export PATH="$HOME/.rbenv/bin:$PATH"
 eval "$(rbenv init -)"
 
-# pyright - 20230811
+# pyright
 export PYRIGHT_PYTHON_FORCE_VERSION="latest"
 
-# pipx - 20231205
+# pipx
 eval "$(register-python-argcomplete pipx)"
 export USE_EMOJI=false
 
-# rust - 20240410
+# rust
+# shellcheck source=/dev/null
 source "$HOME/.cargo/env"
 
-# Go - 20240518
+# Go
 export PATH=$PATH:/usr/local/go/bin
 
+# fzf
+
+# Set the fzf display layout
+export FZF_DEFAULT_OPTS=" \
+  --multi \
+  --height=50% \
+  --margin=5%,2%,2%,5% \
+  --reverse \
+  --preview='(highlight -O ansi {} || bat {}) 2> /dev/null | head -n 50' \
+  --preview-window=45%,border-double --border=double \
+  --prompt='▶' \
+  --pointer='→' \
+  --marker='✗' \
+  --header='CTRL-c or ESC to quit' \
+  --color='dark,fg:magenta,border:cyan'"
+
+# Set the fzf default command
+export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.cache,.git,.ssh,.npm,.vscode,__pycache__,bundle,.mozilla,.ipython,.pip-audit-cache,.yarn,storage,storage2,tmp,bundle,po,htmlcov,staticfiles,migrations,"'
+
+# Set up fzf key bindings and fuzzy completion
+# shellcheck source=/dev/null
+[ -f "$HOME/.config/fzf/fzf.bash" ] && source "$HOME/.config/fzf/fzf.bash"
 
 # ========================================================================= #
 #   Section 3: Special functions
 # ========================================================================= #
 
+# shellcheck source=/dev/null
 if [ -f "$HOME/.bash_aliases" ]; then
     source "$HOME/.bash_aliases"
 fi
 
-if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
+if ! shopt -oq posix; then
+  if [ -f /usr/share/bash-completion/bash_completion ]; then
+    source /usr/share/bash-completion/bash_completion
+  elif [ -f /etc/bash_completion ]; then
     source /etc/bash_completion
+  fi
 fi
-source /etc/bash_completion.d/git-prompt
+
+# shellcheck source=/dev/null
+if [ -f "$HOME/.git-completion.bash" ]; then
+  source "$HOME/.git-completion.bash"
+else
+  echo "WARNING: .git-completion.bash is missing"
+fi
 
 # set a fancy prompt (non-color, unless we know we "want" color)
 case "$TERM" in
@@ -222,9 +256,4 @@ if [ -n "$SSH_CLIENT" ]; then text=" [remote]"
     export PS1='\[\e[01;35m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\w${text}$\[\e[01;37m\] '
 fi
 
-# FZF export layout - 20230325
-export FZF_DEFAULT_OPTS="--multi --height=50% --margin=5%,2%,2%,5% --reverse --preview='(highlight -O ansi {} || bat {}) 2> /dev/null | head -n 50' --preview-window=45%,border-double --border=double --prompt='▶' --pointer='→' --marker='✗' --header='CTRL-c or ESC to quit' --color='dark,fg:magenta,border:green'"
-
-export FZF_DEFAULT_COMMAND='rg --files --hidden -g "!{.git,.ssh,.npm,.vscode,__pycache__,bundle,.mozilla,.ipython,.pip-audit-cache,tmp,bundle,po,htmlcov,staticfiles,migrations}/*"'
-
-[ -f ~/.fzf.bash ] && source "$HOME/.fzf.bash"
+[ -f ~/.fzf.bash ] && source ~/.fzf.bash
